# generated by datamodel-codegen:
#   filename:  b.json
#   timestamp: 2024-10-29T04:06:30+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class PresenceItem(BaseModel):
    class Config:
        extra = 'allow'

    id: str


class Child(BaseModel):
    class Config:
        extra = 'allow'

    id: str
    name: str
    presence: List[PresenceItem]


class AbsentReason(BaseModel):
    class Config:
        extra = 'allow'

    id: str
    name: str
    selected: str


class SchoolQRCodeInfo(BaseModel):
    class Config:
        extra = 'allow'

    translate: dict[str, str]
    child: dict[str, Child]
    absentReasons: List[AbsentReason]
    numChild: int
    schoolDate: str
    schoolhour: str
    hasPresence: bool
    hasQrenable: bool
    qrdate: str
    schoolslug: str
    schoolId: str
    presencein: str
    presenceout: str
    presencesingleurl: str
    presencesinglenoteurl: str
    absenturl: str
    presenceinurl: str
    presenceouturl: str
    multiplePresence: int
    locale: str
    language: str
