name: 👷 publish dev

on:
  push:
    branches:
      - dev
      - dev/*
      - dev-*

jobs:
  test_and_publish:
    name: publish to test.pypi.org
    uses: ./.github/workflows/publish.yml
    with:
      version: '${{ github.run_number }}.0.0'
      repository: testpypi
    secrets:
      twine_username: ${{ secrets.TESTPYPI_USERNAME }}
      twine_password: ${{ secrets.TESTPYPI_PASSWORD }}
