name: publish
run-name: publish to ${{ inputs.repository }}

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      repository:
        type: string
        default: pypi
        required: true
    secrets:
      twine_username:
        required: true
      twine_password:
        required: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  publish:
    name: publish to pypi
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv requirements --dev > reqs.txt
          pip install -r reqs.txt
      - name: force right version
        run: |
          .github/change_version.py --set '${{ inputs.version }}'
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.twine_username }}
          TWINE_PASSWORD: ${{ secrets.twine_password }}
        run: |
          pyproject-build
          twine upload --repository ${{ inputs.repository }} dist/*
