# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: publish dev

on:
  push:
    branches:
      - dev
      - dev/*
      - dev-*

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  publish:
    name: publish to test.pypi.org
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv requirements --dev > reqs.txt
          pip install -r reqs.txt
      - name: set dev version
        run: |
          .github/change_version.py --set '${{ github.run_number }}.0.0'
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_TOKEN }}
        run: |
          pyproject-build
          twine upload --repository testpypi dist/*
