name: 🚀 publish

on:
  release:
    types: [created]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  publish:
    name: publish to pypi
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv requirements --dev > reqs.txt
          pip install -r reqs.txt
      - name: set dev version
        run: |
          .github/change_version.py --set '${{ github.run_number }}.0.0'
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pyproject-build
          twine upload dist/*
