name: 👷 test image

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: test image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: lint check
        run: |
          docker run --rm ghcr.io/fopina/defectdojo-toolkit:${{ steps.sanitize_branch.outputs.sanitized_branch }}  ruff check

      - name: Build and push image - release
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: ghcr.io/fopina/defectdojo-toolkit:latest-build-cache
          tags: |
            ghcr.io/fopina/defectdojo-toolkit:${{ steps.sanitize_branch.outputs.sanitized_branch }}
