name: 👷 test image

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: test image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv requirements --dev > reqs.txt
          pip install -r reqs.txt

      - name: Lint check
        run: |
          make lint-check

      - name: Run unit tests
        run: |
          make test
